name: Transform Error Messages
description: Transform full-length error messages to shortened error messages for production.
author: Philipp Burckhardt <pburckhardt@outlook.com>

runs:
  using: "composite"
  steps:
    - name: Install `jscodeshift` via npm
      run: |
        npm install -g jscodeshift
      shell: bash
    - name: Transform all *.js files with jscodeshift
      run: |
        jscodeshift ./lib/**.js -t ${{ github.action_path }}/transform.js
      shell: bash

branding:
  icon: send
  color: green